apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: default
data:
  # Environment variables
  DATABASE_URL: "jdbc:mysql://example.com:3306/mydb"
  DATABASE_USER: "user123"
  DATABASE_PASSWORD: "pass456"
